//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GM.WindowsUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GM.WindowsUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S2myrsCTbJ+EIEvPxwhK0MdUg7BDQgVxmeeAmo/N1FAROjxKFGdeHX/e3euUTRWHYE+H5GC/QZ6B+Jx/UtExhvXPqV1erPLooUxfZ8F8NjCweMrYU9GHWednygG6SMt/l6OwN6+Dz3Llb9DYmPGl0M4ZDOGptLhHGdB633HXssCpU3vLxpK8WWYPwy1Z8m007cNUxxxKUSWDUnh9j29IMmGUDOziDM/A+4NT+7WTtc4GqKURuBJ9b6F4OsMbdKJXU58BLIfqAEZdLMCQAMCIHisvLu3y8qLUrsgoN5S0dUfvpeT1Diy448+3LbRFb8np6iuA4SP8Y/Xh1B/KZGJi3d+DLeZoC+S6CaQSA+bcTmlOSxr6+kwshRNgZl8Jb5bxTsrCb2Iq9OA+74Ofw64vFZgqZZWpkK4jf2eqRGyOayFENEf2hkGOmOJHgKWav/wGEkEoQZu4Cfe3cY+QPlmjglRaRBgjbDJiO8fTm4nACcdOXIP1K+ozK7lfjY/Xn69e [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string a {
            get {
                return ResourceManager.GetString("a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] gm {
            get {
                object obj = ResourceManager.GetObject("gm", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
