using JWT;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace GM.Api.Tokens
{

    /// <summary>
    /// Body that is encoded into the login and upgrade JWT
    /// </summary>
    public class LoginRequest
    {
        /// <summary>
        /// Client ID from configuration
        /// </summary>
        [JsonProperty("client_id", DefaultValueHandling = DefaultValueHandling.Ignore)]
        public string ClientId { get; set; }

        /// <summary>
        /// A GUID represented as a string, specific to the device
        /// (randomly generated once and saved)
        /// </summary>
        [JsonProperty("device_id", DefaultValueHandling = DefaultValueHandling.Ignore)]
        public string DeviceId { get; set; }

        /// <summary>
        /// OAuth grant type
        /// </summary>
        [JsonProperty("grant_type", DefaultValueHandling = DefaultValueHandling.Ignore)]
        public string GrantType { get; set; }

        /// <summary>
        /// Random string generated by a specifi method
        /// </summary>
        [JsonProperty("nonce", DefaultValueHandling = DefaultValueHandling.Ignore)]
        public string Nonce { get; set; }

        /// <summary>
        /// User's password
        /// </summary>
        [JsonProperty("password", DefaultValueHandling = DefaultValueHandling.Ignore)]
        public string Password { get; set; }

        /// <summary>
        /// Scope
        /// ex: onstar gmoc commerce user_trailer msso
        /// </summary>
        [JsonProperty("scope", DefaultValueHandling = DefaultValueHandling.Ignore)]
        public string Scope { get; set; }

        /// <summary>
        /// Current timestamp in UTC using "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffK" format string
        /// </summary>
        [JsonProperty("timestamp", DefaultValueHandling = DefaultValueHandling.Ignore)]
        public string Timestamp { get; set; }

        /// <summary>
        /// Username for GM account
        /// </summary>
        [JsonProperty("username", DefaultValueHandling = DefaultValueHandling.Ignore)]
        public string Username { get; set; }


        /// <summary>
        /// OnStar PIN used to upgrade token
        /// </summary>
        [JsonProperty("credential", DefaultValueHandling = DefaultValueHandling.Ignore)]
        public string Credential { get; set; }

        /// <summary>
        /// "PIN" for onstar pin
        /// </summary>
        [JsonProperty("credential_type", DefaultValueHandling = DefaultValueHandling.Ignore)]
        public string CredentialType { get; set; }

        /// <summary>
        /// IdToken from login payload - used for refreshing
        /// </summary>
        [JsonProperty("assertion", DefaultValueHandling = DefaultValueHandling.Ignore)]
        public string Assertion { get; set; }


    }





}
